repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: itscontained
    url: https://charts.itscontained.io

releases:
  - name: external-dns
    namespace: externaldns
    chart: bitnami/external-dns
    version: 6.1.8
    values:
      - provider: azure
        azure:
          resourceGroup: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
          tenantId: {{ requiredEnv "AZ_TENANT_ID" }}
          subscriptionId: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
          aadClientId: {{ requiredEnv "SP_CLIENT_ID" }}
          aadClientSecret: {{ requiredEnv "SP_CLIENT_SECRET" }}
          cloud: AzurePublicCloud
        domainFilters:
          - {{ requiredEnv "DOMAIN_NAME" }}
        txtOwnerId: {{ requiredEnv "AZ_AKS_NAME" }}
        policy: sync
        sources:
          - istio-gateway
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}

  - name: istio-base
    namespace: istio-system
    chart: istio/base
    version: 1.13.2

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.13.2
    needs:
      - istio-system/istio-base

  - name: istio-ingress
    namespace: istio-ingress
    chart: istio/gateway
    version: 1.13.2
    needs:
      - istio-system/istiod

  - name: isito-strict-peer-auth
    namespace: istio-system
    chart: itscontained/raw
    version: 0.2.5
    needs: 
      - istio-system/istiod
    values:
      - resources:
          - apiVersion: security.istio.io/v1beta1
            kind: PeerAuthentication
            metadata:
              name: "default"
            spec:
              mtls:
                mode: STRICT

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.7.1
    values:
      - installCRDs: true
        global:
          logLevel: 2

  - name: cert-manager-azure-sp-secret
    namespace: cert-manager
    chart: itscontained/raw
    version: 0.2.5
    needs: 
      - cert-manager/cert-manager
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: cert-manager-azure-sp-secret
            type: Opaque
            stringData:
              sp-client-secret: {{ requiredEnv "SP_CLIENT_SECRET" }}

  - name: cert-manager-issuers
    namespace: cert-manager
    chart: itscontained/raw
    version: 0.2.5
    needs: 
      - cert-manager/cert-manager-azure-sp-secret
    values:
      - resources:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-staging
            spec:
              acme:
                server: https://acme-staging-v02.api.letsencrypt.org/directory
                email: {{ requiredEnv "ACME_ISSUER_EMAIL" }}
                privateKeySecretRef:
                  name: letsencrypt-prod
                solvers:
                  - dns01:
                      azureDNS:
                        clientID: {{ requiredEnv "SP_CLIENT_ID" }}
                        clientSecretSecretRef: 
                          name: cert-manager-azure-sp-secret
                          key: sp-client-secret
                        subscriptionID: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
                        tenantID: {{ requiredEnv "AZ_TENANT_ID" }}
                        resourceGroupName: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
                        hostedZoneName: {{ requiredEnv "DOMAIN_NAME" }}
                        environment: AzurePublicCloud

          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-prod
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                email: {{ requiredEnv "ACME_ISSUER_EMAIL" }}
                privateKeySecretRef:
                  name: letsencrypt-prod
                solvers:
                  - dns01:
                      azureDNS:
                        clientID: {{ requiredEnv "SP_CLIENT_ID" }}
                        clientSecretSecretRef: 
                          name: cert-manager-azure-sp-secret
                          key: sp-client-secret
                        subscriptionID: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
                        tenantID: {{ requiredEnv "AZ_TENANT_ID" }}
                        resourceGroupName: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
                        hostedZoneName: {{ requiredEnv "DOMAIN_NAME" }}
                        environment: AzurePublicCloud
