apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lab4
spec:
  hosts:
  - winegarj.mids-w255.com
  gateways:
  - istio-ingress/winegarj-gateway
  http:
  - match:
    - uri:
        exact: /predict
    - uri:
        prefix: /health
    route:
    - destination:
        host: lab4
        port:
          number: 8000